import type { SpaceItem } from "./types"

export const INDIVIDUAL_SPACES: SpaceItem[] = [
  {
    name: "Office",
    category: "Individual",
    unitSF: 120,
  },
  {
    name: "Workstation",
    category: "Individual",
    unitSF: 42,
  },
  {
    name: "Touchdown",
    category: "Individual",
    unitSF: 30,
  },
]

export const COLLABORATIVE_SPACES: SpaceItem[] = [
  {
    name: "Phone / Focus Booth",
    category: "Collaborative",
    unitSF: 36,
    base: "WS",
    ratio: 10,
    rounding: "ceil",
  },
  {
    name: "Huddle / Flex",
    category: "Collaborative",
    unitSF: 120,
    base: "WS",
    ratio: 15,
    rounding: "ceil",
  },
  {
    name: "Medium Conference",
    category: "Collaborative",
    unitSF: 250,
    base: "S",
    ratio: 40,
    rounding: "ceil",
  },
  {
    name: "Large Conference",
    category: "Collaborative",
    unitSF: 400,
    base: "S",
    ratio: 100,
    rounding: "round",
  },
  {
    name: "Training Room",
    category: "Collaborative",
    unitSF: 600,
    base: "S",
    gate: 60,
  },
  {
    name: "Open Collaboration",
    category: "Collaborative",
    unitSF: 150,
    base: "S",
    ratio: 25,
    rounding: "ceil",
  },
]

export const SUPPORT_SPACES: SpaceItem[] = [
  {
    name: "Reception",
    category: "Support",
    unitSF: 450, // Will be calculated dynamically
    unitBySeatThresholds: [
      { threshold: 0, unitSF: 450 },
      { threshold: 250, unitSF: 900 },
    ],
  },
  {
    name: "Interview Room",
    category: "Support",
    unitSF: 120,
    base: "S",
    ratio: 250,
    rounding: "round",
    gate: 250,
  },
  {
    name: "Multipurpose Room",
    category: "Support",
    unitSF: 1200,
    base: "S",
    ratio: 750,
    rounding: "round",
    gate: 750,
  },
  {
    name: "Work Café / Community Hub",
    category: "Support",
    unitSF: 6, // Per headcount
    base: "HC",
    unitPerHeadcount: true,
  },
  {
    name: "Kitchen Storage",
    category: "Support",
    unitSF: 100,
    base: "S",
    ratio: 100,
    rounding: "round",
  },
  {
    name: "Pantry/Kitchenette",
    category: "Support",
    unitSF: 100,
    base: "S",
    ratio: 80,
    min: 1,
  },
  {
    name: "Quiet Library Space",
    category: "Support",
    unitSF: 500,
    base: "S",
    ratio: 400,
    rounding: "round",
    gate: 400,
  },
  {
    name: "Wellness Room Suite",
    category: "Support",
    unitSF: 300,
    base: "S",
    ratio: 200,
    rounding: "round",
    gate: 200,
  },
  {
    name: "Mothers Room / Suite",
    category: "Support",
    unitSF: 80,
    base: "S",
    ratio: 50,
    rounding: "round",
    gate: 50,
  },
  {
    name: "Coats / Storage Closet",
    category: "Support",
    unitSF: 40,
    base: "S",
    ratio: 50,
    min: 1,
  },
  {
    name: "Workplace Lockers",
    category: "Support",
    unitSF: 5,
    base: "S",
    ratio: 3,
    rounding: "round",
    suppressIfDays: 5,
  },
  {
    name: "Printer / Copy Area",
    category: "Support",
    unitSF: 75,
    base: "S",
    ratio: 50,
    min: 1,
  },
  {
    name: "Mail Room",
    category: "Support",
    unitSF: 300,
    base: "S",
    ratio: 200,
    rounding: "round",
  },
  {
    name: "File Room",
    category: "Support",
    unitSF: 200,
    base: "S",
    ratio: 100,
    rounding: "round",
  },
  {
    name: "Facilities Storage",
    category: "Support",
    unitSF: 150,
    base: "S",
    ratio: 100,
    rounding: "round",
  },
  {
    name: "MDF / Server Room",
    category: "Support",
    unitSF: 150,
    base: "S",
    gate: 150,
  },
  {
    name: "IDF",
    category: "Support",
    unitSF: 80,
    base: "S",
    ratio: 150,
    min: 1,
  },
  {
    name: "IT / Tech Inventory",
    category: "Support",
    unitSF: 120,
    base: "S",
    gate: 300,
  },
  {
    name: "IT Help Desk",
    category: "Support",
    unitSF: 100,
    base: "S",
    gate: 500,
  },
  {
    name: "Internal Stair",
    category: "Support",
    unitSF: 500,
    base: "S",
  },
]

export const CIRCULATION_MULTIPLIERS = {
  individual: 0.67,
  collaborative: 0.67,
  support: 0.54,
}
